#!/usr/bin/env bun

import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { generateBundledVirtualFiles } from "./as/generate-virtual-files";
import {
	COMPILE_TARGETS,
	executableFilenameForTarget,
	RELEASE_COMPILE_TARGETS,
} from "./build-targets";
import {
	isAvailableWazeroAddonTarget,
	resolveCurrentWazeroAddonTarget,
	resolveWazeroAddonTargetForCompileTarget,
	wazeroAddonPathFromCliDir,
} from "./runtime/wazero-targets";

const CLI_DIR = import.meta.dir;
const REPO_DIR = join(CLI_DIR, "..");
const ENTRYPOINT = join(CLI_DIR, "index.ts");
const DIST_DIR = join(CLI_DIR, "dist");
const GENERATED_RUNTIME_DIR = join(CLI_DIR, "runtime", ".generated");
const LOCAL_WAZERO_ADDON_PATH = join(
	REPO_DIR,
	"harness",
	"wazero",
	"dist",
	"wazero.node",
);

function resolveNodeExecutable() {
	const environmentCandidates = [
		process.env.AS_HARNESS_NODE_BINARY,
		process.env.npm_node_execpath,
		process.env.NODE,
	].filter((candidate): candidate is string => Boolean(candidate));

	for (const candidate of environmentCandidates) {
		if (existsSync(candidate)) {
			return candidate;
		}
	}

	const nodeFromPath = Bun.which("node");
	if (nodeFromPath) {
		return nodeFromPath;
	}

	throw new Error(
		[
			"Unable to find a Node executable for the wazero addon build.",
			"Set AS_HARNESS_NODE_BINARY or ensure 'node' is on PATH.",
		].join(" "),
	);
}

function printTargets(targets: readonly string[]) {
	for (const target of targets) {
		console.log(target);
	}
}

async function cleanDist() {
	await rm(DIST_DIR, { recursive: true, force: true });
}

function resolveTargets(args: string[]) {
	if (args.includes("--list-targets")) {
		printTargets(COMPILE_TARGETS);
		process.exit(0);
	}

	if (args.includes("--list-release-targets")) {
		printTargets(RELEASE_COMPILE_TARGETS);
		process.exit(0);
	}

	if (args.includes("--clean")) {
		return { cleanOnly: true, targets: [] as Bun.Build.CompileTarget[] };
	}

	if (args.includes("--release-targets")) {
		return {
			cleanOnly: false,
			targets: [...RELEASE_COMPILE_TARGETS],
		};
	}

	if (args.length === 0) {
		return { cleanOnly: false, targets: COMPILE_TARGETS };
	}

	const validTargets = new Set(COMPILE_TARGETS);
	const invalidTargets = args.filter(
		(target) => !validTargets.has(target as Bun.Build.CompileTarget),
	);

	if (invalidTargets.length > 0) {
		console.error(`Unknown compile target(s): ${invalidTargets.join(", ")}`);
		console.error(
			"Run 'bun run build:list-targets' to see the supported target list.",
		);
		process.exit(1);
	}

	return { cleanOnly: false, targets: args as Bun.Build.CompileTarget[] };
}

function outputPathForTarget(target: Bun.Build.CompileTarget) {
	return join(DIST_DIR, target, executableFilenameForTarget(target));
}

async function buildTarget(
	target: Bun.Build.CompileTarget,
	wazeroTarget: string,
	wazeroEmbeddedModulePath: string | null,
	index: number,
	total: number,
) {
	const outfile = outputPathForTarget(target);
	await mkdir(dirname(outfile), { recursive: true });

	console.log(`[${index}/${total}] building ${target}`);

	const processHandle = Bun.spawn(
		[
			process.execPath,
			"build",
			"--compile",
			`--target=${target}`,
			`--outfile=${outfile}`,
			`--define=WAZERO_TARGET="${wazeroTarget}"`,
			`--define=WAZERO_EMBEDDED_MODULE_PATH=${JSON.stringify(wazeroEmbeddedModulePath)}`,
			ENTRYPOINT,
		],
		{
			cwd: CLI_DIR,
			stdout: "inherit",
			stderr: "inherit",
			stdin: "inherit",
		},
	);

	const exitCode = await processHandle.exited;
	return { exitCode, outfile, target };
}

async function ensureLocalWazeroAddonBuilt() {
	if (existsSync(LOCAL_WAZERO_ADDON_PATH)) {
		return;
	}

	console.log("building local wazero addon for CLI packaging");

	const processHandle = Bun.spawn(
		[resolveNodeExecutable(), "./scripts/build.mjs"],
		{
			cwd: join(REPO_DIR, "harness", "wazero"),
			stderr: "inherit",
			stdin: "inherit",
			stdout: "inherit",
		},
	);

	const exitCode = await processHandle.exited;
	if (exitCode !== 0) {
		throw new Error("Failed to build the local wazero addon.");
	}
}

async function generateEmbeddedWazeroModule(
	wazeroTarget: string,
	addonPath: string,
) {
	const encodedAddon = (await readFile(addonPath)).toString("base64");
	await mkdir(GENERATED_RUNTIME_DIR, { recursive: true });
	const moduleFilename = `wazero-embedded-${wazeroTarget}.ts`;
	const modulePath = join(GENERATED_RUNTIME_DIR, moduleFilename);
	await writeFile(
		modulePath,
		[
			"// This file is generated by cli/build.ts.",
			`export default ${JSON.stringify(encodedAddon)};`,
			"",
		].join("\n"),
		"utf8",
	);
	return `./.generated/${moduleFilename}`;
}

async function prepareWazeroAddonForTarget(target: Bun.Build.CompileTarget) {
	const wazeroTarget = resolveWazeroAddonTargetForCompileTarget(target);
	if (!isAvailableWazeroAddonTarget(wazeroTarget)) {
		return { wazeroEmbeddedModulePath: null, wazeroTarget };
	}

	const outputPath = wazeroAddonPathFromCliDir(CLI_DIR, wazeroTarget);
	if (resolveCurrentWazeroAddonTarget() !== wazeroTarget) {
		if (existsSync(outputPath)) {
			return {
				wazeroEmbeddedModulePath: await generateEmbeddedWazeroModule(
					wazeroTarget,
					outputPath,
				),
				wazeroTarget,
			};
		}

		console.warn(
			`wazero addon for ${target} is not staged at ${outputPath}; building this CLI target without bundled wazero support.`,
		);
		return {
			wazeroEmbeddedModulePath: null,
			wazeroTarget: "unavailable",
		};
	}

	await ensureLocalWazeroAddonBuilt();
	await mkdir(dirname(outputPath), { recursive: true });
	await copyFile(LOCAL_WAZERO_ADDON_PATH, outputPath);
	return {
		wazeroEmbeddedModulePath: await generateEmbeddedWazeroModule(
			wazeroTarget,
			outputPath,
		),
		wazeroTarget,
	};
}

async function main() {
	const { cleanOnly, targets } = resolveTargets(process.argv.slice(2));
	const failures: Bun.Build.CompileTarget[] = [];

	await cleanDist();

	if (cleanOnly) {
		console.log(`Removed ${DIST_DIR}/`);
		return;
	}

	await generateBundledVirtualFiles();

	for (const [index, target] of targets.entries()) {
		const { wazeroEmbeddedModulePath, wazeroTarget } =
			await prepareWazeroAddonForTarget(target);
		const result = await buildTarget(
			target,
			wazeroTarget,
			wazeroEmbeddedModulePath,
			index + 1,
			targets.length,
		);
		if (wazeroTarget !== "unavailable") {
			console.log(`bundled wazero addon target for ${target}: ${wazeroTarget}`);
		}

		if (result.exitCode !== 0) {
			failures.push(target);
		}
	}

	if (failures.length > 0) {
		console.error("");
		console.error(`Failed targets (${failures.length}/${targets.length}):`);
		for (const target of failures) {
			console.error(`- ${target}`);
		}
		process.exit(1);
	}

	console.log("");
	console.log(`Built ${targets.length} executable target(s) into ${DIST_DIR}/`);
}

await main();
