export declare function createHarness(
	bytes: import("../shared/harness-types").HarnessBytes,
): import("../shared/harness-types").Harness;

export type {
	Harness,
	HarnessBranch,
	HarnessBranchDiscovery,
	HarnessBytes,
	HarnessCoverageFileOverview,
	HarnessCoverageJSONFile,
	HarnessCoverageJSONReport,
	HarnessCoveragePoint,
	HarnessCoveragePointEntry,
	HarnessCoveragePointType,
	HarnessCoverageSnapshot,
	HarnessCallbackEvent,
	HarnessDiagnosticEvent,
	HarnessEvent,
	HarnessEventCallback,
	HarnessEventMap,
	HarnessEventType,
	HarnessExecution,
	HarnessFailMessageEvent,
	HarnessLogEvent,
	HarnessNode,
	HarnessNodeEvent,
	HarnessNodeFoundEvent,
	HarnessStartResult,
} from "../shared/harness-types";
