import { expect, test } from "bun:test";
import { renderWasmtimeLicenseInventory } from "./generate-wasmtime-license-inventory";

test("renderWasmtimeLicenseInventory summarizes direct deps, counts, and crate rows", () => {
	const rendered = renderWasmtimeLicenseInventory({
		packages: [
			{
				dependencies: [
					{ kind: null, name: "anyhow", req: "^1.0.100" },
					{ kind: "build", name: "napi-build", req: "^2.3.1" },
				],
				license: "MIT",
				name: "as-harness-wasmtime",
				version: "0.1.0",
			},
			{
				dependencies: [],
				license: "MIT OR Apache-2.0",
				name: "anyhow",
				repository: "https://github.com/dtolnay/anyhow",
				source: "registry+https://github.com/rust-lang/crates.io-index",
				version: "1.0.102",
			},
			{
				dependencies: [],
				license: "MIT",
				name: "napi-build",
				repository: "https://github.com/napi-rs/napi-rs",
				source: "registry+https://github.com/rust-lang/crates.io-index",
				version: "2.3.1",
			},
		],
	});

	expect(rendered).toContain(
		"generated by scripts/generate-wasmtime-license-inventory.ts",
	);
	expect(rendered).toContain(
		"| `anyhow` | `^1.0.100` | `1.0.102` | `normal` | `MIT OR Apache-2.0` | <https://github.com/dtolnay/anyhow> |",
	);
	expect(rendered).toContain("| `MIT` | 1 |");
	expect(rendered).toContain("| `MIT OR Apache-2.0` | 1 |");
	expect(rendered).toContain(
		"| `napi-build` | `2.3.1` | `MIT` | `crates.io` | <https://github.com/napi-rs/napi-rs> |",
	);
});
