#!/usr/bin/env bun

import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { REPO_DIR } from "./legal-metadata";

type CargoMetadataDependency = {
	kind: "build" | "dev" | null;
	name: string;
	req: string;
};

type CargoMetadataPackage = {
	dependencies: CargoMetadataDependency[];
	homepage?: string | null;
	license?: string | null;
	name: string;
	repository?: string | null;
	source?: string | null;
	version: string;
};

type CargoMetadata = {
	packages: CargoMetadataPackage[];
};

export const WASMTIME_LICENSE_INVENTORY_PATH = join(
	REPO_DIR,
	"licenses",
	"wasmtime",
	"THIRD_PARTY_INVENTORY.md",
);

const WASMTIME_HOST_DIR = join(REPO_DIR, "harness", "wasmtime");
const WASMTIME_ROOT_PACKAGE_NAME = "as-harness-wasmtime";

function commandLabel(command: string[]) {
	return command.join(" ");
}

async function runCommand(command: string[], cwd: string) {
	const process = Bun.spawn(command, {
		cwd,
		stderr: "inherit",
		stdout: "pipe",
	});
	const stdout = await new Response(process.stdout).text();
	const exitCode = await process.exited;

	if (exitCode !== 0) {
		throw new Error(
			`Command failed with exit code ${exitCode}: ${commandLabel(command)}`,
		);
	}

	return stdout;
}

function escapeTableCell(value: string | null | undefined) {
	return (value ?? "").replaceAll("|", "\\|");
}

function packageSourceLabel(pkg: CargoMetadataPackage) {
	if (!pkg.source) {
		return "workspace";
	}

	if (pkg.source.includes("crates.io")) {
		return "crates.io";
	}

	return pkg.source;
}

function packageUpstreamUrl(pkg: CargoMetadataPackage) {
	return pkg.repository ?? pkg.homepage ?? "";
}

export async function loadWasmtimeCargoMetadata(): Promise<CargoMetadata> {
	const stdout = await runCommand(
		["cargo", "metadata", "--format-version", "1", "--locked"],
		WASMTIME_HOST_DIR,
	);
	return JSON.parse(stdout) as CargoMetadata;
}

export function renderWasmtimeLicenseInventory(metadata: CargoMetadata) {
	const rootPackage = metadata.packages.find(
		(pkg) => pkg.name === WASMTIME_ROOT_PACKAGE_NAME,
	);
	if (!rootPackage) {
		throw new Error(
			`Unable to find ${JSON.stringify(WASMTIME_ROOT_PACKAGE_NAME)} in cargo metadata.`,
		);
	}

	const crates = metadata.packages
		.filter(
			(pkg) =>
				pkg.name !== WASMTIME_ROOT_PACKAGE_NAME &&
				(pkg.source?.includes("crates.io") ?? false),
		)
		.sort(
			(left, right) =>
				left.name.localeCompare(right.name) ||
				left.version.localeCompare(right.version),
		);

	const directDependencies = rootPackage.dependencies
		.map((dependency) => {
			const resolvedPackage = crates.find(
				(pkg) => pkg.name === dependency.name,
			);
			return {
				kind: dependency.kind ?? "normal",
				license: resolvedPackage?.license ?? "UNKNOWN",
				name: dependency.name,
				repository:
					resolvedPackage?.repository ?? resolvedPackage?.homepage ?? "",
				req: dependency.req,
				version: resolvedPackage?.version ?? "UNKNOWN",
			};
		})
		.sort(
			(left, right) =>
				left.kind.localeCompare(right.kind) ||
				left.name.localeCompare(right.name),
		);

	const licenseCounts = new Map<string, number>();
	for (const pkg of crates) {
		const license = pkg.license ?? "UNKNOWN";
		licenseCounts.set(license, (licenseCounts.get(license) ?? 0) + 1);
	}

	const licenseRows = [...licenseCounts.entries()].sort(([left], [right]) =>
		left.localeCompare(right),
	);

	const lines = [
		"<!-- This file is generated by scripts/generate-wasmtime-license-inventory.ts. -->",
		"",
		"# Wasmtime Third-Party Inventory",
		"",
		"This inventory covers the source-build `wasmtime` host in",
		"`harness/wasmtime`. It is generated from",
		"`cargo metadata --format-version 1 --locked` and is not the packaged",
		"release notice file for `as-harness`.",
		"",
		"## Direct Dependencies",
		"",
		"| Crate | Requirement | Resolved | Kind | License | Upstream |",
		"| --- | --- | --- | --- | --- | --- |",
		...directDependencies.map(
			(dependency) =>
				`| \`${escapeTableCell(dependency.name)}\` | \`${escapeTableCell(dependency.req)}\` | \`${escapeTableCell(dependency.version)}\` | \`${escapeTableCell(dependency.kind)}\` | \`${escapeTableCell(dependency.license)}\` | ${dependency.repository ? `<${escapeTableCell(dependency.repository)}>` : ""} |`,
		),
		"",
		"## License Expression Counts",
		"",
		"| License expression | Count |",
		"| --- | ---: |",
		...licenseRows.map(
			([license, count]) => `| \`${escapeTableCell(license)}\` | ${count} |`,
		),
		"",
		"## Locked Crate Inventory",
		"",
		"| Crate | Version | License | Source | Upstream |",
		"| --- | --- | --- | --- | --- |",
		...crates.map(
			(pkg) =>
				`| \`${escapeTableCell(pkg.name)}\` | \`${escapeTableCell(pkg.version)}\` | \`${escapeTableCell(pkg.license ?? "UNKNOWN")}\` | \`${escapeTableCell(packageSourceLabel(pkg))}\` | ${packageUpstreamUrl(pkg) ? `<${escapeTableCell(packageUpstreamUrl(pkg))}>` : ""} |`,
		),
		"",
	];

	return lines.join("\n");
}

async function main() {
	const metadata = await loadWasmtimeCargoMetadata();
	const rendered = renderWasmtimeLicenseInventory(metadata);
	await mkdir(dirname(WASMTIME_LICENSE_INVENTORY_PATH), { recursive: true });
	await Bun.write(WASMTIME_LICENSE_INVENTORY_PATH, rendered);
	console.log(`Wrote ${WASMTIME_LICENSE_INVENTORY_PATH}`);
}

if (import.meta.main) {
	await main();
}
