import { expect, test } from "bun:test";
import {
	parseBunLockPackageVersion,
	parseGoModuleVersion,
	parseMiseToolVersion,
	renderThirdPartyNotices,
} from "./legal-metadata";

test("parseBunLockPackageVersion resolves versions from the locked npm closure", () => {
	expect(
		parseBunLockPackageVersion(
			'"assemblyscript": ["assemblyscript@0.28.10", "", {}]',
			"assemblyscript",
		),
	).toBe("0.28.10");
});

test("parseGoModuleVersion resolves direct and indirect module versions", () => {
	expect(
		parseGoModuleVersion(
			[
				"require github.com/tetratelabs/wazero v1.11.0",
				"",
				"require golang.org/x/sys v0.38.0 // indirect",
			].join("\n"),
			"golang.org/x/sys",
		),
	).toBe("v0.38.0");
});

test("parseMiseToolVersion resolves pinned toolchain versions", () => {
	expect(parseMiseToolVersion('bun = "1.3.11"', "bun")).toBe("1.3.11");
});

test("renderThirdPartyNotices includes the lockfile-backed packaged versions", () => {
	const rendered = renderThirdPartyNotices({
		assemblyscriptVersion: "0.28.10",
		binaryenVersion: "123.0.0-nightly.20250530",
		bunVersion: "1.3.11",
		longVersion: "5.3.2",
		wazeroVersion: "v1.11.0",
		xSysVersion: "v0.38.0",
	});

	expect(rendered).toContain(
		"generated by scripts/sync-third-party-notices.ts",
	);
	expect(rendered).toContain("`123.0.0-nightly.20250530`");
	expect(rendered).toContain("`5.3.2`");
	expect(rendered).toContain("`v1.11.0`");
	expect(rendered).toContain("`1.3.11`");
});
