import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const REPO_DIR = join(import.meta.dir, "..");
export const THIRD_PARTY_NOTICES_PATH = join(
	REPO_DIR,
	"THIRD_PARTY_NOTICES.md",
);

export type PackagedLegalSnapshot = {
	wazeroVersion: string;
	wasmtimeVersion: string;
	xSysVersion: string;
};

function escapeRegExp(pattern: string) {
	return pattern.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function captureVersion(contents: string, pattern: RegExp, label: string) {
	const match = contents.match(pattern);
	const version = match?.[1]?.trim();
	if (!version) {
		throw new Error(
			`Unable to resolve ${label} version from tracked metadata.`,
		);
	}
	return version;
}

export function parseGoModuleVersion(
	goModContents: string,
	moduleName: string,
) {
	const escapedModuleName = escapeRegExp(moduleName);
	return captureVersion(
		goModContents,
		new RegExp(
			`(?:^|\\n)(?:require\\s+)?${escapedModuleName}\\s+(v[^\\s]+)`,
			"m",
		),
		moduleName,
	);
}

export function parseCargoDependencyVersion(
	cargoTomlContents: string,
	dependencyName: string,
) {
	const escapedDependencyName = escapeRegExp(dependencyName);
	return captureVersion(
		cargoTomlContents,
		new RegExp(`^${escapedDependencyName}\\s*=\\s*"(.*?)"$`, "m"),
		dependencyName,
	);
}

export async function loadPackagedLegalSnapshot(
	repoDir: string = REPO_DIR,
): Promise<PackagedLegalSnapshot> {
	const [goModContents, wasmtimeCargoTomlContents] = await Promise.all([
		readFile(join(repoDir, "harness", "wazero", "go.mod"), "utf8"),
		readFile(join(repoDir, "harness", "wasmtime", "Cargo.toml"), "utf8"),
	]);

	return {
		wazeroVersion: parseGoModuleVersion(
			goModContents,
			"github.com/tetratelabs/wazero",
		),
		wasmtimeVersion: parseCargoDependencyVersion(
			wasmtimeCargoTomlContents,
			"wasmtime",
		),
		xSysVersion: parseGoModuleVersion(goModContents, "golang.org/x/sys"),
	};
}

export function renderThirdPartyNotices(snapshot: PackagedLegalSnapshot) {
	const lines = [
		"<!-- This file is generated by scripts/sync-third-party-notices.ts. -->",
		"",
		"# Third-Party Notices",
		"",
		"This file identifies the third-party software redistributed in the current",
		"public npm package line for `as-harness`.",
		"",
		"This file covers public npm package artifacts only:",
		"",
		"- the `wazero` native host packages",
		"- the `wasmtime` native host packages",
		"",
		"`@as-harness/cli` now expects `assemblyscript` to be installed by the",
		"consumer as a peer dependency, so the CLI package does not redistribute the",
		"AssemblyScript compiler closure itself. The project remains MIT licensed",
		"under [LICENSE](./LICENSE).",
		"",
		"## Public Npm Components",
		"",
		"### wazero",
		"",
		"- Project: `github.com/tetratelabs/wazero`",
		`- Version: \`${snapshot.wazeroVersion}\``,
		"- License: `Apache-2.0`",
		"- Included texts:",
		"  - [licenses/wazero/LICENSE](./licenses/wazero/LICENSE)",
		"  - [licenses/wazero/NOTICE](./licenses/wazero/NOTICE)",
		"- Repository: <https://github.com/tetratelabs/wazero>",
		"- Release scope: per-platform `@as-harness/wazero-*` npm packages",
		"",
		"### golang.org/x/sys",
		"",
		"- Project: `golang.org/x/sys`",
		`- Version: \`${snapshot.xSysVersion}\``,
		"- License: BSD-style license from the Go authors",
		"- Included text:",
		"  - [licenses/golang.org-x-sys/LICENSE](./licenses/golang.org-x-sys/LICENSE)",
		"- Repository: <https://go.googlesource.com/sys>",
		"- Release scope: per-platform `@as-harness/wazero-*` npm packages",
		"",
		"### wasmtime",
		"",
		"- Project: `wasmtime`",
		`- Version: \`${snapshot.wasmtimeVersion}\``,
		"- License: `Apache-2.0 WITH LLVM-exception`",
		"- Repository: <https://github.com/bytecodealliance/wasmtime>",
		"- Release scope: per-platform `@as-harness/wasmtime-*` npm packages",
		"- Dependency inventory:",
		"  [licenses/wasmtime/THIRD_PARTY_INVENTORY.md](./licenses/wasmtime/THIRD_PARTY_INVENTORY.md)",
		"  is staged with the npm package legal bundle for the public release line.",
		"",
		"## Public Npm Package Layout",
		"",
		"Each staged npm package includes the project `LICENSE`, this notice file,",
		"and the tracked `wasmtime` inventory file.",
		"",
		"The native host packages additionally carry the tracked upstream license texts",
		"for the code they redistribute.",
		"",
		"## Source-Only Components Not Bundled In Public Npm Packages",
		"",
		"The following repo components are not bundled into the public npm packages",
		"described above:",
		"",
		"- consumer-installed `assemblyscript` and its dependency closure",
		"- development-only tooling such as `@biomejs/biome` and `@types/bun`",
		"",
		"Those components may still need their own inventory and compliance handling,",
		"but they are not part of the public npm artifacts described in this file.",
		"",
	];

	return lines.join("\n");
}
