import { expect, test } from "bun:test";
import {
	parseCargoDependencyVersion,
	parseGoModuleVersion,
	renderThirdPartyNotices,
} from "./legal-metadata";

test("parseGoModuleVersion resolves direct and indirect module versions", () => {
	expect(
		parseGoModuleVersion(
			[
				"require github.com/tetratelabs/wazero v1.11.0",
				"",
				"require golang.org/x/sys v0.38.0 // indirect",
			].join("\n"),
			"golang.org/x/sys",
		),
	).toBe("v0.38.0");
});

test("parseCargoDependencyVersion resolves manifest dependency versions", () => {
	expect(parseCargoDependencyVersion('wasmtime = "34.0.2"', "wasmtime")).toBe(
		"34.0.2",
	);
});

test("renderThirdPartyNotices includes the lockfile-backed npm release versions", () => {
	const rendered = renderThirdPartyNotices({
		wazeroVersion: "v1.11.0",
		wasmtimeVersion: "34.0.2",
		xSysVersion: "v0.38.0",
	});

	expect(rendered).toContain(
		"generated by scripts/sync-third-party-notices.ts",
	);
	expect(rendered).toContain("`v1.11.0`");
	expect(rendered).toContain("`34.0.2`");
	expect(rendered).toContain("peer dependency");
});
