#!/usr/bin/env bun

import { mkdir, readdir, writeFile } from "node:fs/promises";
import { posix, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const OUTPUT_FILE = resolve(import.meta.dir, "virtual-files.generated.ts");
const GENERATED_DIR = resolve(import.meta.dir, ".generated");
const BARREL_FILE = resolve(GENERATED_DIR, "virtual-files.barrel.ts");
const ASSEMBLY_SOURCE_DIR = resolve(
	import.meta.dir,
	"..",
	"..",
	"assembly",
	"assembly",
);
const VIRTUAL_ROOT = "~/.as-harness";

async function collectAssemblySourceFiles(dirname: string): Promise<string[]> {
	const entries = await readdir(dirname, { withFileTypes: true });
	const files: string[] = [];

	for (const entry of entries) {
		const entryPath = resolve(dirname, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await collectAssemblySourceFiles(entryPath)));
			continue;
		}

		if (entry.isFile() && entry.name.endsWith(".ts")) {
			files.push(entryPath);
		}
	}

	return files.sort();
}

function toPosixPath(path: string): string {
	return path.replaceAll("\\", "/");
}

function variableNameForIndex(index: number): string {
	return `virtualFile${index}`;
}

function renderVirtualFilesBarrel(sourceFiles: readonly string[]): string {
	const importLines = sourceFiles.map((sourceFile, index) => {
		const importPath = toPosixPath(relative(GENERATED_DIR, sourceFile));
		return `import ${variableNameForIndex(index)} from "${importPath}" with { type: "text" };`;
	});

	const mapEntries = sourceFiles.map((sourceFile, index) => {
		const relativePath = toPosixPath(relative(ASSEMBLY_SOURCE_DIR, sourceFile));
		return `\t[\`${VIRTUAL_ROOT}/${relativePath}\`, ${variableNameForIndex(index)}],`;
	});

	return `// This file is generated by cli/as/generate-virtual-files.ts.
// Do not edit it by hand.

${importLines.join("\n")}

export const bundledVirtualRoot = "${VIRTUAL_ROOT}";

export const bundledVirtualFiles = new Map<string, string>([
${mapEntries.join("\n")}
]);
`;
}

function renderVirtualFilesModule(
	bundledVirtualFiles: ReadonlyMap<string, string>,
): string {
	const mapEntries = [...bundledVirtualFiles.entries()]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([virtualPath, contents]) =>
				`\t[${JSON.stringify(virtualPath)}, ${JSON.stringify(contents)}],`,
		);

	return `// This file is generated by cli/as/generate-virtual-files.ts.
// Do not edit it by hand.

export const bundledVirtualRoot = ${JSON.stringify(VIRTUAL_ROOT)};

export const bundledVirtualFiles = new Map<string, string>([
${mapEntries.join("\n")}
]);
`;
}

export async function generateBundledVirtualFiles(): Promise<void> {
	const sourceFiles = await collectAssemblySourceFiles(ASSEMBLY_SOURCE_DIR);
	await mkdir(GENERATED_DIR, { recursive: true });
	await writeFile(BARREL_FILE, renderVirtualFilesBarrel(sourceFiles), "utf8");

	const barrelUrl = pathToFileURL(BARREL_FILE);
	barrelUrl.searchParams.set("t", String(Date.now()));
	const barrelModule = (await import(barrelUrl.href)) as {
		bundledVirtualFiles: Map<string, string>;
	};
	const output = renderVirtualFilesModule(barrelModule.bundledVirtualFiles);
	await writeFile(OUTPUT_FILE, output, "utf8");
}

if (import.meta.main) {
	await generateBundledVirtualFiles();
}
