#!/usr/bin/env bun

import { mkdir, readdir, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const CLI_DIR = resolve(import.meta.dir, "..");
const OUTPUT_FILE = resolve(import.meta.dir, "virtual-files.generated.ts");
const GENERATED_DIR = resolve(import.meta.dir, ".generated");
const BARREL_FILE = resolve(GENERATED_DIR, "virtual-files.barrel.ts");
const ASSEMBLY_SOURCE_DIR = resolve(
	import.meta.dir,
	"..",
	"..",
	"assembly",
	"assembly",
);
const TRANSFORM_SOURCE_DIR = resolve(import.meta.dir, "..", "transform", "src");
const VIRTUAL_ROOT = "~/.as-harness";
const TRANSFORM_VIRTUAL_ROOT = `${VIRTUAL_ROOT}/transform`;
const BIOME_BIN = resolve(
	CLI_DIR,
	"node_modules",
	"@biomejs",
	"biome",
	"bin",
	"biome",
);

const transformTranspiler = new Bun.Transpiler({
	loader: "ts",
});

async function collectSourceFiles(dirname: string): Promise<string[]> {
	const entries = await readdir(dirname, { withFileTypes: true });
	const files: string[] = [];

	for (const entry of entries) {
		const entryPath = resolve(dirname, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await collectSourceFiles(entryPath)));
			continue;
		}

		if (entry.isFile() && entry.name.endsWith(".ts")) {
			files.push(entryPath);
		}
	}

	return files.sort();
}

function toPosixPath(path: string): string {
	return path.replaceAll("\\", "/");
}

function variableNameForIndex(index: number): string {
	return `virtualFile${index}`;
}

function renderImports(sourceFiles: readonly string[], offset = 0): string[] {
	return sourceFiles.map((sourceFile, index) => {
		const importPath = toPosixPath(relative(GENERATED_DIR, sourceFile));
		return `import ${variableNameForIndex(offset + index)} from "${importPath}" with { type: "text" };`;
	});
}

function assemblyVirtualPathsFor(relativePath: string): string[] {
	const defaultVirtualPath = `${VIRTUAL_ROOT}/${relativePath}`;

	switch (relativePath) {
		case "lib/node_assert.ts":
			return [defaultVirtualPath, `${VIRTUAL_ROOT}/lib/node:assert.ts`];
		case "lib/node_assert/legacy.ts":
			return [defaultVirtualPath, `${VIRTUAL_ROOT}/lib/node:assert/legacy.ts`];
		case "lib/node_assert/shared.ts":
			return [defaultVirtualPath, `${VIRTUAL_ROOT}/lib/node:assert/shared.ts`];
		case "lib/node_assert/strict.ts":
			return [defaultVirtualPath, `${VIRTUAL_ROOT}/lib/node:assert/strict.ts`];
		case "lib/node_test_lib.ts":
			return [defaultVirtualPath, `${VIRTUAL_ROOT}/lib/node:test.ts`];
		default:
			return [defaultVirtualPath];
	}
}

function renderAssemblyMapEntries(sourceFiles: readonly string[]): string[] {
	return sourceFiles.flatMap((sourceFile, index) => {
		const relativePath = toPosixPath(relative(ASSEMBLY_SOURCE_DIR, sourceFile));
		return assemblyVirtualPathsFor(relativePath).map(
			(virtualPath) =>
				`\t[\`${virtualPath}\`, ${variableNameForIndex(index)}],`,
		);
	});
}

function replaceExtension(path: string, extension: string): string {
	return path.replace(/\.[^.]+$/, extension);
}

function renderTransformMapEntries(
	sourceFiles: readonly string[],
	offset: number,
): string[] {
	return sourceFiles.map((sourceFile, index) => {
		const relativePath = replaceExtension(
			toPosixPath(relative(TRANSFORM_SOURCE_DIR, sourceFile)),
			".js",
		);
		return `\t[\`${TRANSFORM_VIRTUAL_ROOT}/${relativePath}\`, ${variableNameForIndex(offset + index)}],`;
	});
}

function renderVirtualFilesBarrel(
	assemblySourceFiles: readonly string[],
	transformSourceFiles: readonly string[],
): string {
	const importLines = [
		...renderImports(assemblySourceFiles),
		...renderImports(transformSourceFiles, assemblySourceFiles.length),
	];
	const assemblyEntries = renderAssemblyMapEntries(assemblySourceFiles);
	const transformEntries = renderTransformMapEntries(
		transformSourceFiles,
		assemblySourceFiles.length,
	);

	return `// biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated transform source bundle
// This file is generated by cli/as/generate-virtual-files.ts.
// Do not edit it by hand.

${importLines.join("\n")}

export const bundledVirtualRoot = "${VIRTUAL_ROOT}";

export const bundledVirtualFiles = new Map<string, string>([
${assemblyEntries.join("\n")}
]);

export const bundledTransformRoot = "${TRANSFORM_VIRTUAL_ROOT}";

export const bundledTransformSources = new Map<string, string>([
${transformEntries.join("\n")}
]);
`;
}

function renderVirtualFilesModule(
	bundledVirtualFiles: ReadonlyMap<string, string>,
	bundledTransformFiles: ReadonlyMap<string, string>,
): string {
	const virtualFileEntries = [...bundledVirtualFiles.entries()]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([virtualPath, contents]) =>
				`\t[${JSON.stringify(virtualPath)}, ${JSON.stringify(contents)}],`,
		);
	const transformEntries = [...bundledTransformFiles.entries()]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([virtualPath, contents]) =>
				`\t[${JSON.stringify(virtualPath)}, ${JSON.stringify(contents)}],`,
		);

	return `// biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated transform source bundle
// This file is generated by cli/as/generate-virtual-files.ts.
// Do not edit it by hand.

export const bundledVirtualRoot = ${JSON.stringify(VIRTUAL_ROOT)};

export const bundledVirtualFiles = new Map<string, string>([
${virtualFileEntries.join("\n")}
]);

export const bundledTransformRoot = ${JSON.stringify(TRANSFORM_VIRTUAL_ROOT)};

export const bundledTransformFiles = new Map<string, string>([
${transformEntries.join("\n")}
]);
`;
}

async function formatGeneratedTypescriptFile(filePath: string): Promise<void> {
	const processHandle = Bun.spawn(
		[process.execPath, BIOME_BIN, "format", "--write", filePath],
		{
			cwd: CLI_DIR,
			stderr: "inherit",
			stdin: "inherit",
			stdout: "inherit",
		},
	);

	const exitCode = await processHandle.exited;
	if (exitCode !== 0) {
		throw new Error(`Failed to format generated file: ${filePath}`);
	}
}

export async function generateBundledVirtualFiles(): Promise<void> {
	const assemblySourceFiles = await collectSourceFiles(ASSEMBLY_SOURCE_DIR);
	const transformSourceFiles = await collectSourceFiles(TRANSFORM_SOURCE_DIR);
	await mkdir(GENERATED_DIR, { recursive: true });
	await writeFile(
		BARREL_FILE,
		renderVirtualFilesBarrel(assemblySourceFiles, transformSourceFiles),
		"utf8",
	);

	const barrelUrl = pathToFileURL(BARREL_FILE);
	barrelUrl.searchParams.set("t", String(Date.now()));
	const barrelModule = (await import(barrelUrl.href)) as {
		bundledVirtualFiles: Map<string, string>;
		bundledTransformSources: Map<string, string>;
	};
	const bundledTransformFiles = new Map<string, string>(
		[...barrelModule.bundledTransformSources.entries()].map(
			([virtualPath, contents]) => [
				virtualPath,
				transformTranspiler.transformSync(contents),
			],
		),
	);
	const output = renderVirtualFilesModule(
		barrelModule.bundledVirtualFiles,
		bundledTransformFiles,
	);
	await writeFile(OUTPUT_FILE, output, "utf8");
	await formatGeneratedTypescriptFile(OUTPUT_FILE);
}

if (import.meta.main) {
	await generateBundledVirtualFiles();
}
